Global:
  tmppath: tmp
  forcerun: False
  threads: 3
  poll_timeout: 15
  wait_timeout: 900

Sandvine:
  export:
    http:
      path: tmp/urls.lst
      cutproto: False
    https:
      path: tmp/https.lst
      cutproto: False
    domain:
      path: tmp/domains.lst
      collapse: True
      extra: https
    wdomain:
      path: tmp/wdomains.lst
      collapse: True
      wc_asterize: True
    ipv4:
      path: tmp/ips.lst
      collapse: True
      subnet_fmt: False
      extra: [https, domain, domain-mask]
    ipv6:
      path: tmp/ipv6s.lst
      collapse: True
      subnet_fmt: False
      extra: [https, domain, domain-mask]

API:
  host: 10.1.253.90
  port: 80
  url: /cgi-bin/rknget/rkn/webjsonapi.py
  secure: false
  timeout: 720

Logging:
  logpath: ./rkn-sandvine.log
  stdoutlvl: WARN
  logfilelvl: DEBUG
