Global:
  tmppath: tmp
  forcerun: False
  threads: 3
  poll_timeout: 15
  wait_timeout: 900

Sandvine:
  export:
    http:
      path: tmp/urls.lst
      truncate_proto: False
    https:
      path: tmp/https.lst
      only_sni: True
      from_domains: False
    domain:
      path_domain: tmp/domains.lst
      collapse: True
      path_wdomain: tmp/wdomains.lst
      asterize_wc: False
      sort: True
    ipv4:
      path: tmp/ips.lst
      collapse: True
      subnet_fmt: False
    ipv6:
      path: tmp/ipv6s.lst
      collapse: True
      subnet_fmt: False

API:
  host: 10.1.253.90
  port: 80
  url: /cgi-bin/rknget/rkn/webjsonapi.py
  secure: false
  timeout: 720

Logging:
  logpath: ./rkn-sandvine.log
  stdoutlvl: WARN
  logfilelvl: DEBUG
