Global:
  tmppath: ./tmp
  forcerun: False

Bird:
  restartcmd: service bird restart
  confpath: ./bird-rkn.conf
  stubip: 1.1.1.1

API:
  host: 10.1.241.154
  port: 80
  url: /cgi-bin/rknget/rkn/webapi.py
  secure: false
  timeout: 720

Logging:
  logpath: ./rkn-bird.log
  stdoutlvl: DEBUG
  logfilelvl: INFO

