Global:
  tmppath: ./tmp
  forcerun: False
  saveconf: True

Bird:
  restartcmd: systemctl reload bird
  confpath: ./bird-rkn.conf
  collapse: True
  stubip: 1.1.1.1
  ipv6: False
  limit: 950000

API:
  host: 10.1.253.90
  port: 80
  url: /cgi-bin/rknget/rkn/webjsonapi.py
  secure: false
  timeout: 720

Extra:
  - https
  - domain
  - domain-mask

Logging:
  logpath: ./rkn-bird.log
  stdoutlvl: DEBUG
  logfilelvl: INFO

