Global:
  tmppath: ./tmp
  forcerun: False
  saveconf: True

Bird:
  restartcmd: /etc/init.d/bird restart
  confpath: ./bird-rkn.conf
  collapse: False
  stubip: 1.1.1.1

API:
  host: 10.1.253.90
  port: 80
  url: /cgi-bin/rknget/rkn/webjsonapi.py
  secure: false
  timeout: 720

Logging:
  logpath: ./rkn-bird.log
  stdoutlvl: DEBUG
  logfilelvl: INFO

