Global:
  tmppath: ./tmp
  statepath: ./state.yml

Bird:
  restartcmd: service bird restart
  confpath: ./rkn-bird.conf
  stubip: 1.1.1.1

DB:
  engine: postgresql
  host: 10.1.241.154
  port: 5432
  dbname: rkndb
  user: rkn
  password: hry

Logging:
  logpath: ./rkn-bird.log
  stdoutlvl: DEBUG
  logfilelvl: INFO

