Global:
  tmppath: ./tmp
  statepath: ./state.yml
  savetmp: True

Unbound:
  binarypath: /usr/sbin/unbound-control
  confpath: ./rkn.conf
  stubip: 10.1.1.3

DB:
  engine: postgresql
  host: localhost
  port: 5432
  dbname: rkndb
  user: rkn
  password: hry

Logging:
  logpath: ./rkn-unbound.log
  stdoutlvl: DEBUG
  logfilelvl: INFO

