Global:
  tmppath: ./tmp
  statepath: ./state.yml
  forcerun: False

Unbound:
  binarypath: /usr/sbin/unbound-control
  confpath: ./rkn.conf
  stubip: 10.1.1.3

API:
  host: 10.1.241.154
  port: 80
  url: /cgi-bin/rknget/rkn/webapi.py
  secure: false
  timeout: 720

Logging:
  logpath: ./rkn-unbound.log
  stdoutlvl: DEBUG
  logfilelvl: INFO

