Global:
  tmppath: ./tmp
  forcerun: False
  saveconf: True

Unbound:
  binarypath: /usr/sbin/unbound-control
  confpath: ./rkn.conf
  collapse: True
  stubip: 10.1.1.3
  stubipv6: None

API:
  host: 10.1.253.90
  port: 80
  url: /cgi-bin/rknget/rkn/webjsonapi.py
  secure: false
  timeout: 720

Logging:
  logpath: ./rkn-unbound.log
  stdoutlvl: DEBUG
  logfilelvl: INFO

