Global:
  forcerun: False

F5:
  - host: 127.0.0.1
    port: 8443
    secure: true
    datagroup: rcn_group
    user: admin
    password: password
    timeout: 60
  - host: 127.0.0.1
    port: 9443
    secure: true
    datagroup: rcn_group
    user: admin
    password: password
    timeout: 60

Extra:
  https: True
  ip: True
  ipsubnet: False
  domain: True
  domain-mask: True
  truncate-after: 200000

API:
  host: 10.1.253.90
  port: 80
  url: /cgi-bin/rknget/rkn/webjsonapi.py
  secure: false
  timeout: 720

Logging:
  logpath: ./rkn-f5.log
  stdoutlvl: DEBUG
  logfilelvl: INFO

