Global:
  tmppath: ./tmp
  forcerun: False

F5:
  - host: 127.0.0.1
    port: 8443
    secure: true
    datagroup: rcn_group
    user: admin
    password: admin
    timeout: 60
  - host: 127.0.0.1
    port: 9443
    secure: true
    datagroup: rcn_group
    user: admin
    password: admin
    timeout: 60
#  - host: 10.1.1.210
#    port: 443
#    secure: true
#    datagroup: rcn_group
#    user: rkn
#    password: FG3xm$0Tdn
#    timeout: 60
#  - host: 10.1.1.211
#    port: 443
#    secure: true
#    datagroup: rcn_group
#    user: rkn
#    password: FG3xm$0Tdn
#    timeout: 60

Extra:
  https: True
  ip: True
  ipsubnet: False
  domain: True
  domain-mask: True
  truncate-after: 200000

API:
  host: 10.1.241.154
  port: 80
  url: /cgi-bin/rknget/rkn/webapi.py
  secure: false
  timeout: 720

Logging:
  logpath: ./rkn-f5.log
  stdoutlvl: DEBUG
  logfilelvl: INFO

