Global:
  tmppath: ./tmp
  statepath: ./state.yml
  pidpath: ./.pid
  savetmp: True
  reqPath: ./request.xml
  reqPathSig: ./request.xml.sig

DumpLoader:
  url: http://vigruzki.rkn.gov.ru/services/OperatorRequest/?wsdl
  retrycount: 5
  conntimeout: 240
  sleeptimeout: 60
  SoapVersion: 1.2
  dumpfmtver: 2.3

DB:
  engine: postgresql
  host: localhost
  port: 5432
  dbname: rkndb
  user: rkn
  password: hry

Blocking:
  basic: True
  dnsfromhttps: True
  ipfromhttps: True
  ipfromdnsmask: True


Miscellaneous:
  Synthetic: False

Logging:
  logpath: ./rknget.log
  stdoutlvl: INFO
  logfilelvl: INFO

Debug:
  useTempDump: True
  useTempData: False
