Global:
  tmpPath: ./tmp
  savedump: True
  dumpPath: ./tmp/dump.xml.zip
  reqPath: ./request.xml
  reqPathSig: ./request.xml.sig
  forcerun: False

DumpLoader:
  url: http://vigruzki.rkn.gov.ru/services/OperatorRequest/?wsdl
  retrycount: 5
  conntimeout: 240
  sleeptimeout: 60
  SoapVersion: 1.2
  dumpfmtver: 2.3

DB:
  engine: postgresql
  host: 10.1.241.154
  port: 5432
  dbname: rkndb
  user: rkn
  password: hry

Blocking:
  - [https, domain]
  - [https, ip]
  - [domain-mask, ip]

Miscellaneous:
  custom: True
  uselocaldump: False

Logging:
  logpath: ./rknget.log
  stdoutlvl: INFO
  logfilelvl: INFO
