Global:
  tmppath: ./tmp
  savedump: True
  dumpPath: ./tmp/dump.xml.zip
  reqPath: ./request.xml
  reqPathSig: ./request.xml.sig
  forcerun: False

DumpLoader:
  url: http://vigruzki.rkn.gov.ru/services/OperatorRequest/?wsdl
  retrycount: 5
  conntimeout: 240
  sleeptimeout: 60
  SoapVersion: 1.2
  dumpfmtver: 2.3

API:
  host: 10.1.241.154
  port: 80
  url: /cgi-bin/rknget/rkn/webjsonapi.py
  secure: false
  timeout: 720

Blocking:
  - [https, domain]
  - [https, ip]
  - [domain-mask, ip]

Miscellaneous:
  custom: True
  uselocaldump: False

Logging:
  logpath: ./rknget.log
  stdoutlvl: INFO
  logfilelvl: INFO
