Global:
  tmppath: ./tmp
  statepath: ./state.yml
  savetmp: True
  reqPath: ./request.xml
  reqPathSig: ./request.xml.sig

DumpLoader:
  url: http://vigruzki.rkn.gov.ru/services/OperatorRequest/?wsdl
  retrycount: 5
  conntimeout: 240
  sleeptimeout: 60
  SoapVersion: 1.2
  dumpfmtver: 2.3

# Deprecated
DataMapping:
  http:
    - out/http.lst
  https:
    - out/https.lst
  domain:
    - out/domain.lst
  domainmask:
    - out/domain.lst
  ip:
    - out/ipsub.lst
  ipsub:
    - out/ipsub.lst

DB:
  engine: postgresql
  host: localhost
  port: 5432
  dbname: rkndb
  user: rkn
  password: hry

Blocking:
  basic: True
  dnsfromhttps: True
  ipfromhttps: True
  ipfromdnsmask: True


Miscellaneous:
  Synthetic: False

Logging:
  logpath: ./rknget.log
  stdoutlvl: INFO
  logfilelvl: INFO

Debug:
  useTempDump: True
  useTempData: False
